### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/unified-graphics#35]
## Problem

We make use of mocks in our unit tests to avoid having to maintain large data files in Git for test fixtures. Mocks provide good isolation for our unit tests and make it easy to test different conditions for each function, but they can mask errors caused by changes to dependencies because those dependencies are mocked in the tests.

## Solution

Write integration tests that run in a production-like environment with no mocks to ensure that everything is connected together. We will create test data for the integration tests (as opposed to using real data) so that we can control our test conditions, but the data will be stored in S3 the same way we store production data to ensure our ability to read the data is also working.

## No Gos

Describe any features or behaviors that have been considered and rejected as out of scope for this project.

## Tasks

- [ ] Create an S3 bucket for integration test fixtures
- [ ] Create test data for temperature diag data
- [ ] Add integration test for temperature diagnostic end point

**Comment by ian-noaa** [comment]
An S3 bucket has been created for us at: `s3://osti-modeling-dev-rtma-vis/`. I've uploaded the diag files we received from Guoqing to a `diag-demo-files` directory in the bucket. However, we may want to create our own test data instead of using those diag files.

**Comment by esheehan-gsl** [comment]
Yeah, I think you’re right about creating our own test files. We’ll probably want smaller, less complicated files for testing.
