### ISSUE TITLE
Archive the project

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/unified-graphics#538]
## Describe the motivation for the change

The decision has been made to sunset the project. We'd like to preserve samples of the data, and archive the project.

## Describe the change

```[tasklist]
### Tasks
- [x] Preserve samples of our input data (diagnostic netCDF files)
- [ ] Extract samples of our application data (Zarr array, Parquet tables, and SQL database
- [ ] Give VLab the go ahead to turn off services & destroy data
- [ ] Update the README to call out that the project has ended
- [ ] Archive the project
```
