### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/unified-graphics#57]
## Problem

In order to help us ensure we’re testing well we should measure code coverage in our tests.

## Solution

Add `coverage` to the Python services and use [Vitest’s built-in coverage](https://vitest.dev/guide/coverage.html) support.

## No Gos

None.

## Rabbit Holes

None

## Tasks

- [x] Add `coverage` as a dev dependency to `services/api`
- [x] Run `coverage` in CI
- [x] Run `vitest run --coverage` in CI
